version: '3.7'

services:
  dns:
    container_name: dnsmasq
    build:
      context: ./services/dnsmasq
      dockerfile: andyshinn.Dockerfile
    ports:
      # - 53:53/tcp
      # - 53:53/udp
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./services/dnsmasq/volumes/etc/dnsmasq:/etc/dnsmasq
      - ./services/dnsmasq/volumes/etc/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - frontend

  redis:
    container_name: Redis
    restart: always
    build: 
      context: ./services/redis
      dockerfile: 4.0.8.Dockerfile
      args:
        TZ: "Asia/Seoul"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      # - redisdata:/data/redis
      # - type: volume
      #   source: redisdata
      #   target: /data/redis
      #   volume:
      #     nocopy: true
      - type: bind
        source: ./volumes/redis
        target: /data/redis
    networks:
      - backend

  nginx:
    container_name: Nginx
    restart: always
    build: 
      context: ./services/nginx
      dockerfile: 1.14.0.Dockerfile
      args:
        TZ: "Asia/Seoul"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./services/nginx/volumes/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./services/nginx/volumes/etc/nginx/inc.d:/etc/nginx/inc.d
      - ./services/nginx/volumes/etc/nginx/keys:/etc/nginx/keys
      - ./services/nginx/volumes/etc/nginx/logs:/etc/nginx/logs
      - ./services/nginx/volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/var/log/nginx:/var/log/nginx
    networks:
      - frontend

  misagotools:
    container_name: misagotools
    restart: always
    build:
      context: ./services/misagotools
      dockerfile: "Laradock.php-fpm.2.4.Dockerfile"
      args:
        TZ: "Asia/Seoul"
        LARADOCK_PHP_VERSION: "7.0"
        INSTALL_ZIP_ARCHIVE: "true"
        INSTALL_PHPREDIS: "true"
        INSTALL_MYSQLI: "true"
        INSTALL_INTL: "true"
        INSTALL_FAKETIME: "true"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      # - ./services/misagotools/volumes/composer:/composer
      - ./services/misagotools/volumes/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./services/misagotools/volumes/etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./services/misagotools/volumes/etc/php/conf.d/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
      - ./services/misagotools/volumes/etc/php/conf.d/xlaravel.pool.conf:/usr/local/etc/php-fpm.d/xlaravel.pool.conf
    ports:
      - 9000:9000
    networks:
      - frontend
    links:
      - redis
    depends_on:
      - redis

#  application:
#   dns:
#    - 8.8.8.8
#    - 4.4.4.4
#    - 192.168.9.45
#   volumes_from:
#     - nexus-data
#   networks:
#     - pic

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  # pic:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 172.18.0.0/16
  #         gateway: 172.18.0.1





# volumes:
#   mongodbdata:
#     driver: local
#   redisdata:
#     driver: local
#   maildata:
#     driver: local
#   mailstate:
#     driver: local
