version: '3.7'

services:
  dns:
    container_name: dnsmasq
    build:
      context: ./services/dnsmasq
      dockerfile: andyshinn.Dockerfile
    ports:
      # - 53:53/tcp
      # - 53:53/udp
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./services/dnsmasq/volumes/etc/dnsmasq:/etc/dnsmasq
      - ./services/dnsmasq/volumes/etc/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - frontend

  redis:
    container_name: Redis
    restart: always
    build: 
      context: ./services/redis/4.0.8
      dockerfile: redis.Dockerfile
      args:
        TZ: "Asia/Seoul"
    volumes:
      # - redisdata:/data/redis
      # - type: volume
      #   source: redisdata
      #   target: /data/redis
      #   volume:
      #     nocopy: true
      - type: bind
        source: ./volumes/redis
        target: /data/redis
    networks:
      - backend

  nginx:
    container_name: Web
    restart: always
    build: 
      context: ./services/nginx/1.14.0
      dockerfile: nginx.Dockerfile
      args:
        TZ: "Asia/Seoul"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/1.14.0/volumes/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./services/nginx/1.14.0/volumes/etc/nginx/inc.d:/etc/nginx/inc.d
      - ./services/nginx/1.14.0/volumes/etc/nginx/keys:/etc/nginx/keys
      - ./services/nginx/1.14.0/volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - /var/www:/var/www
    networks:
      - frontend
    links:
      - misagotools
      - atlassianconfluenceserver

  misagotools:
    container_name: misagotools
    restart: always
    build:
      context: ./services/misagotools
      dockerfile: Laradock.php-fpm.2.4.Dockerfile
      args:
        TZ: "Asia/Seoul"
        LARADOCK_PHP_VERSION: "7.0"
        INSTALL_ZIP_ARCHIVE: "true"
        INSTALL_PHPREDIS: "true"
        INSTALL_MYSQLI: "true"
        INSTALL_INTL: "true"
        INSTALL_FAKETIME: "true"
    volumes:
      - ./services/misagotools/volumes/composer:/composer
      - ./services/misagotools/volumes/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./services/misagotools/volumes/etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./services/misagotools/volumes/etc/php/conf.d/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
      - ./services/misagotools/volumes/etc/php/conf.d/xlaravel.pool.conf:/usr/local/etc/php-fpm.d/xlaravel.pool.conf
      - ./volumes/nginx/var/log/nginx:/var/log/nginx
      - /var/www/misagotools:/var/www/misagotools
    # ports:
    #   - 9000:9000
    networks:
      - frontend
    links:
      - redis
    depends_on:
      - redis

  confluencedb:
    container_name: ConfluenceDB
    restart: always
    build:
      context: ./services/postgresql/10.4
      dockerfile: postgresql.Dockerfile
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - /data/docker/postgresql:/var/lib/postgresql
    # ports:
    #   - 5432:5432
    networks:
      - backend

  atlassianconfluenceserver:
    container_name: AtlassianConfluenceServer
    restart: always
    build:
      context: ./services/confluence/7.0.1
      dockerfile: atlassian.confluence-server.Dockerfile
      args:
        CONFLUENCE_VERSION: 7.0.1
    volumes:
      - /data/docker/confluence:/var/atlassian/application-data/confluence
      # - ./services/confluence/7.0.1/opt/atlassian/confluence/conf/server.misagotools.xml:/opt/atlassian/confluence/conf/server.xml
    environment:
      JVM_MAXIMUM_MEMORY: 2G
      CATALINA_CONNECTOR_SECURE: "false"
      CATALINA_CONNECTOR_PROXYPORT: 80
      CATALINA_CONNECTOR_SCHEME: http
      CATALINA_CONNECTOR_PROXYNAME: atlassianconfluenceserver
    #   JVM_SUPPORT_RECOMMENDED_ARGS: "-Djavax.net.ssl.trustStore=/var/atlassian/application-data/jira/cacerts"
    # ports:
    #   - 8090:8090
    #   - 8091:8091
    networks:
      - frontend
    links:
      - confluencedb
    depends_on:
      - confluencedb

#  application:
#   dns:
#    - 8.8.8.8
#    - 4.4.4.4
#    - 192.168.9.45
#   volumes_from:
#     - nexus-data
#   networks:
#     - pic

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  # pic:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 172.18.0.0/16
  #         gateway: 172.18.0.1





# volumes:
#   mongodbdata:
#     driver: local
#   redisdata:
#     driver: local
#   maildata:
#     driver: local
#   mailstate:
#     driver: local
